FROM python:3.9

ARG GRADIO_SERVER_PORT=8080
ENV GRADIO_SERVER_PORT=${GRADIO_SERVER_PORT}

RUN apt update && \
    apt install -y --no-install-recommends \
        wget \
        libglib2.0-0 \
        ca-certificates && \
    rm -rf /var/lib/apt/lists/*


# Install necessary packages
RUN apt-get update && apt-get install -y \
    ffmpeg \
    libsm6 \
    libxext6 \
    libfontconfig1 \
    libxrender1 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

ADD requirements.txt visual_chatgpt.py /workspace/

RUN pip install -r /workspace/requirements.txt

CMD ["python", "visual_chatgpt.py", "--load", "ImageCaptioning_cpu,Text2Image_cpu"]
